Rich picture
UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy pull request #18
Opened 2023-04-18 00:30 UTC by pedroblome

Criação do artefato de rich picture

- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have read the CONTRIBUTING.md doc.
- [x] I have added necessary documentation (if appropriate).
- [x] Any dependent changes have been merged and published in downstream modules.

2023-04-18 12:18 UTC, nszchagas commented
Pessoal, só solicitei uma alteração, em relação à imagem, fora isso o trabalho está excelente. Assim que atualizarem a imagem para uma versão mais nítida podem dar merge. :)

2023-04-18 12:19 UTC, nszchagas requested changes

2023-04-18 23:10 UTC, lucasgcaldas commented on docs/Files/RichPicture/Rich_Picture_Inicial_Baixa.jpg
Beleza, tenho q alterar o outro desenho tbm, escrevi RiHappy errado.

2023-04-20 00:36 UTC, lucasgcaldas commented
@nszchagas atualizei as imagens, confere ai por favor.

2023-04-20 14:49 UTC, merged