[FEAT] VIsão de Dados (DAS)
UnBArqDsw2023-1/2023.1_G5_ProjetoRiHappy pull request #88
Opened 2023-06-26 11:35 UTC by nszchagas

Descreva as mudanças efetuadas de forma breve.

## Issue relacionada

Esse PR se refere à issue #{insira o número da issue}

## Tipo de mudança

- [ ] Feature
- [ ] Bug
- [ ] Outra: {insira descrição}

## Tarefas antes de marcar o PR como pronto

- [ ] Conferi que a minha branch está atualizada com a `main`;
- [ ] Meu PR é para a branch `main`;
- [ ] Coloquei o número da issue relacionada na seção acima;
- [ ] As alterações da minha branch com a main são relacionadas APENAS ao tema do PR.

2023-06-26 15:46 UTC, daves22 requested changes

2023-06-26 15:46 UTC, daves22 commented on docs/4.arquiteturareutilizacao/padroes/padroesarquiteturais.md
> +article {counter-reset:section figuras;}
Acho que essa alteração está dando erro, no mkdocs. N sei se é na minha maquina mas não custa dar uma olhada novamente para ver se precisa corrigir.

2023-06-26 16:12 UTC, nszchagas commented on docs/4.arquiteturareutilizacao/padroes/padroesarquiteturais.md
> +article {counter-reset:section figuras;}
Essa alteração troca o contador de figuras do body para o article, creio que não seja isso. Qual erro você teve? Pra rodar a documentação basta rodar `npm install` e depois `npm start` na raiz do projeto, você pode testar de novo aí por favor? Qualquer erro só mandar aqui que a gente debuga junto. :)

2023-06-27 16:57 UTC, daves22 approved these changes

2023-06-27 16:57 UTC, merged